export const stats = [
  {
    id: 1,
    title: "Erhalt der Studienanfrage",
    checked: true,
    field: "erhalt",
    description: "erhalt_description",
    date: null,
  },
  {
    id: 2,
    title: "Meldung an die/den Studienbeauftragten (Ärztliche Direktion)",
    checked: false,
    field: "meldung",
    description: "meldung_description",
    date: null,
  },
  {
    id: 3,
    title: "Vorprüfung der Machbarkeit und Ressourcenverfügbarkeit",
    checked: false,
    field: "vorprufung",
    description: "vorprufung_description",
    date: null,
  },
  {
    id: 4,
    title:
      "Zur Kenntnisnahme an die ärztliche Abteilungsleitung (falls nicht identisch dem PI)",
    checked: false,
    field: "kenntnisnahme",
    description: "kenntnisnahme_description",
    date: null,
  },
  {
    id: 5,
    title:
      "Detailprüfung der Studienunterlagen – Studienbeauftragte*r (Ärztliche Direktion)",
    checked: false,
    field: "detailprufung",
    description: "detailprufung_description",
    date: null,
  },
  {
    id: 6,
    title: "Vorprüfung und Freigabe durch die Ärztliche Direktion",
    checked: false,
    field: "freigabe",
    description: "freigabe_description",
    date: null,
  },
  {
    id: 7,
    title:
      "Bewertung der ethischen und datenschutzrechtlichen Anforderungen – Studienbeauftragte*r(Ärztliche Direktion)",
    checked: false,
    field: "bewertung",
    description: "bewertung_description",
    date: null,
  },
  {
    id: 8,
    title:
      "Genehmigung durch die*den Datenschutzbeauftragte*n für Klinische Studien",
    checked: false,
    field: "genehmigung",
    description: "genehmigung_description",
    date: null,
  },
  {
    id: 9,
    title: "Verhandlung der Vertragsbedingungen",
    checked: false,
    field: "verhandlung",
    description: "verhandlung_description",
    date: null,
  },
  {
    id: 10,
    title: "Festlegung des Budgets und finanzieller Rahmenbedingungen",
    checked: false,
    field: "festlegung",
    description: "festlegung_description",
    date: null,
  },
  {
    id: 11,
    title: "Abschluss der Verträge",
    checked: false,
    field: "abschluss",
    description: "abschluss_description",
    date: null,
  },
  {
    id: 12,
    title: "Vorbereitung der Studie",
    checked: false,
    field: "vorbereitung",
    description: "vorbereitung_description",
    date: null,
  },
  {
    id: 13,
    title: "Studieninitiierung",
    checked: false,
    field: "studien",
    description: "studien_description",
    date: null,
  },
  {
    id: 14,
    title: "Durchführung des First Patient First Visit (FPFV)",
    checked: false,
    field: "durchfuhrung",
    description: "durchfuhrung_description",
    date: null,
  },
  {
    id: 15,
    title: "Patientenanzahl im Screening 1. Monat",
    checked: false,
    field: "patienten_one",
    description: "patienten_one_description",
    date: null,
  },
  {
    id: 16,
    title: "Stand der Randomisierung 1. Monat",
    checked: false,
    field: "stand_one",
    description: "stand_one_description",
    date: null,
  },
  {
    id: 17,
    title: "Patientenanzahl im Screening 2. Monat",
    checked: false,
    field: "patienten_two",
    description: "patienten_two_description",
    date: null,
  },
  {
    id: 18,
    title: "Stand der Randomisierung 2. Monat",
    checked: false,
    field: "stand_two",
    description: "stand_two_description",
    date: null,
  },
  {
    id: 19,
    title: "Patientenanzahl im Screening 3. Monat",
    checked: false,
    field: "patienten_three",
    description: "patienten_three_description",
    date: null,
  },
  {
    id: 20,
    title: "Stand der Randomisierung 3. Monat",
    checked: false,
    field: "stand_three",
    description: "stand_three_description",
    date: null,
  },
  {
    id: 21,
    title: "Übernahme der vollständigen Studien-Checkliste",
    checked: false,
    field: "ubernahme",
    description: "ubernahme_description",
    date: null,
  },
];
